name: Pipeline DevSecOps
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcb80e669f # v5.1.1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install --only-binary :all: -r requirements.txt || pip install -r requirements.txt

  sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92 # v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=tsymike
            -Dsonar.projectKey=tsyMike_app-vulnerable-sesion4

  sca:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: snyk/actions/python@b2da123f1e96a40a6b4b45efae9bb5e9d970e5b0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}